---
title: "Homework5"
author: Jyoti Kumar
output: github_document
---

```{r}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


# Problem1

The Raw Data gives us information on the homicide cases in 50 large US cities. The Data gives us information on the date reported, victims name, race, age and sex. It provides us with the city, the latitude and longitude information and the disposition of the case. 

```{r}
homicide_df = 
  read_csv("data/homicide-data.csv") %>% 
  mutate(
    city_state = str_c(city, state, sep = "_"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "Unsolved",
      disposition == "Open/No arrest"        ~ "Unsolved",
      disposition == "Closed by arrest"      ~ "solved"
    )
  ) %>%
  select(city_state, resolved) %>% 
  filter(city_state != "Tulsa_AL")
```


```{r}
aggregate_df =
  homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    hom_total = n(),
    hom_unsolved = sum(resolved != "solved")
  )
```


```{r}
prop.test(
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_unsolved),
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_total)) %>% 
  broom::tidy()
```

```{r}
results_df =
aggregate_df %>%
  mutate(
    prop_tests = map2(.x = hom_unsolved, .y = hom_total, ~prop.test(x = .x, n = .y)),
    tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))
  ) %>% 
  select(-prop_tests) %>% 
  unnest(tidy_tests) %>% 
  select(city_state, estimate, conf.low, conf.high )
```


```{r}
results_df %>%
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

# Problem2

```{r}
data1 = read.csv("data/problem2data/con_01.csv")
```


```{r}
path_df =
  tibble(
    files = list.files("data/problem2data"),
    path = str_c("data/problem2data/", files)) %>% 
      mutate(data = map(path, read_csv, col_types = "dddddddd")) %>% 
  unnest()
```

```{r}
path_df %>% 
  pivot_longer(week_1:week_8, names_to = "week", values_to = "outcome", names_prefix = "week_") %>% 
  mutate(
    week = as.numeric(week)
  ) %>% 
ggplot(aes(x = week, y = outcome, color = files)) + geom_point() + geom_path()
```


# Problem3

```{r}
sim_t_test = function(n_samp = 30, mu = 2, sigma = 5) {
 
  sim_data = tibble(
    x = rnorm(n_samp, mean = mu, sd = sigma)
  )
 
  test = t.test(x ~ 1, data = sim_data)
 
  broom::tidy(test)
  
}
```

